/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 env_ground_3.glb --transform --shadows -D 
Files: env_ground_3.glb [10.87MB] > /Users/pirouzm/Documents/github/para/public/env_ground_3-transformed.glb [776.5KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { position, scale = [1, 1, 1] } = props;

  const { nodes } = useGLTF('/env_ground_3-transformed.glb')
  const materialProps = {
    metalness: 0,
    roughness: 0.6,
    ior: 1.1,
    color: "#101010",
    flatShading: false,
    reflectivity: 0,
  }
  return (
    <group scale={scale} position={position} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} >
        <meshPhysicalMaterial {...materialProps} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/env_ground_3-transformed.glb')
