/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oval_bag_3.glb --instance --shadows --transform 
Files: oval_bag_3.glb [330.04KB] > /Users/pirouzm/Documents/github/para/public/oval_bag_3-transformed.glb [44.32KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/oval_bag_3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bag_9_for_web.geometry} material={materials['black  matte tpu']} />
    </group>
  )
}

useGLTF.preload('/oval_bag_3-transformed.glb')
