import { UnifrakturCook } from "next/font/google"
import "./globals.css";
import NavBar from "./components/NavBar"
const cook = UnifrakturCook({ weight: '700', subsets: ["latin"], });

export const metadata = {
    title: "App Main",
    description: "Generated by create next app",
};

// <body
//     className={`min-h-screen max-h-screen min-w-screen max-w-screen bg-[radial-gradient(ellipse_at_50%_100%,_var(--tw-gradient-stops))] from-clay_dark via-tahiti via-40% to-clay_dark to-100% backdrop-filter backdrop-contrast-125"
//         ${cook.className}`}
// >
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className ={`bg-slate-50 ${cook.className}`}>
            <NavBar />
                {children}
            </body>
        </html>
    );
}
