import './globals.css';
import localFont from 'next/font/local';
// import Header from './components/Header';

const myFont = localFont({
  src: './../../public/fonts/halibutSerif/web/HalibutSerif-Condensed.woff2',
  display: 'swap',
});

export const metadata = {
  title: '℘讠 ⍨',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-cover bg-[#bcbcbc]`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
