import { UnifrakturCook, Noto_Sans } from "next/font/google";

import "./globals.css";
import NavBar from "./components/NavBar";
import Header from "./components/Header";

// const cook = UnifrakturCook({ weight: "700", subsets: ["latin"] });
const noto = Noto_Sans({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "℘讠 ⍨",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${noto.className} bg-cover bg-default-background-image`}
        // className={`${cook.className} bg-cover bg-default-background-image`}
      >
        <NavBar />
        {/* <Header /> */}

        {children}
      </body>
    </html>
  );
}
